---
apiVersion: v1
kind: Pod
metadata:
  name: kube-doom-pod
  namespace: kubedoom
spec:
  hostNetwork: true
  serviceAccountName: kubedoom
  containers:
  - image: storaxdev/kubedoom:0.5.0
    name: kubedoom
    ports:
      - containerPort: 5900
        protocol: TCP
 